name: eurocup_frontend
description: Events platform for organizing competitions.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.18.0
  image_picker:
  flutter_launcher_icons: ^0.13.1
#  flutter_secure_storage: ^8.0.0
  mobile_scanner: ^3.2.0
  flutter_barcode_scanner: ^2.0.0
  qrscan: ^0.3.3
  printing: ^5.11.0
  permission_handler: ^10.3.0
  url_launcher: ^6.0.9
  file_picker: ^4.0.0
  universal_html: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/unknown.png
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"